services:
  - type: web
    name: trikon-backend
    env: python
    region: singapore
    plan: free
    buildCommand: pip install -r api/requirements.txt
    startCommand: python -m uvicorn api.app:app --host 0.0.0.0 --port 10000
    envVars:
      - key: SCARF_NO_ANALYTICS
        value: "true"
